### PR TITLE
Fix website color theme

### LINKED ISSUE #13: social media icons are not viewable
colors style needs to be updated

Screen Shot 2022-10-24 at 2 08 03 PM

### PR DESCRIPTION
**Pull request by purna135**
Fixes #13 

Hi @cuchoi, I used the provided colour as well as some extra colour, and the result can be found here, https://purna135.github.io/pymcon-test 
Please take a look and let me know if this will work; otherwise, we can try another colour combination.

Also, in this PR, I rearranged the organisers so that all Team Leads are in the first row; please let me know if this is acceptable.

### CODE REVIEW

**Comment by OriolAbril** [comment]
Looks great, thanks. My only comment is updating the yellowish text in the donation section as it is hard to read due to lack of contrast. The one in "payment options" and "pros".

**Comment by purna135** [comment]
https://purna135.github.io/pymcon-test/, I used a different color combination here; could you help me figure out which one is best or suggest a different color code to use?

image

**Comment by purna135** [comment]
I think keeping the test color white is a good choice.

**Comment by cuchoi** [comment]
All the changes look great to me! Thank you @purna135.

**Review by cuchoi — APPROVED** [review]

**Pull request merged**
